"""Add goal_grade to Unit model

Revision ID: 4ba1fa7f3f2e
Revises: fb10d9cffaa4
Create Date: 2025-05-07 18:47:54.338776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ba1fa7f3f2e'
down_revision = 'fb10d9cffaa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_grade', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.drop_column('goal_grade')

    # ### end Alembic commands ###
