"""empty message

Revision ID: 746b33800a32
Revises: d61cc7b464eb
Create Date: 2025-05-16 15:11:56.081295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746b33800a32'
down_revision = 'd61cc7b464eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_access', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_selection', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_access', schema=None) as batch_op:
        batch_op.drop_column('unit_selection')

    # ### end Alembic commands ###
