"""Ensure models are up-to-date

Revision ID: 8f7a2088d171
Revises: 4ba1fa7f3f2e
Create Date: 2025-05-08 18:12:17.449755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f7a2088d171'
down_revision = '4ba1fa7f3f2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('date', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('unit_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'unit', ['unit_id'], ['id'])

    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('outline_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.drop_column('outline_url')
        batch_op.drop_column('target_score')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('unit_id')
        batch_op.drop_column('date')
        batch_op.drop_column('task_name')

    # ### end Alembic commands ###
