"""Enable cascade delete for tasks when deleting units

Revision ID: d61cc7b464eb
Revises: 71ae023fb41e
Create Date: 2025-05-16 11:01:25.269338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd61cc7b464eb'
down_revision = '71ae023fb41e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_unit_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_task_unit_id', 'unit', ['unit_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_unit_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_task_unit_id', 'unit', ['unit_id'], ['id'])

    # ### end Alembic commands ###
